// <auto-generated />
namespace FlightSearch.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewColumnAirlineSchedueSTOPSAMOUNT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumnAirlineSchedueSTOPSAMOUNT));
        
        string IMigrationMetadata.Id
        {
            get { return "202101141032190_New-Column-AirlineSchedue-STOPS-AMOUNT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
