// <auto-generated />
namespace FlightSearch.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class NewTableAirlineSchedulesAndTableNameUpdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewTableAirlineSchedulesAndTableNameUpdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202101140831306_New-Table-AirlineSchedules-And-Table-Name-Updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
